version: '3.4'

services:
  gatway-api:
    build:
      context: ./gatway-api
    ports:
      - "8080:8080"

  challenge-api:
    build:
      context: ./challenge-api

  bet-api:
    build:
      context: ./bet-api

  auth-api:
    build:
      context: ./auth-api

  user-api:
    build:
      context: ./user-api